### ISSUE TITLE
Tipping outside of Steam Group

### ISSUE THREAD

**Issue by VootLejin** [petschekr/SteamDogeTipBot#11]
It would be useful if the bot could send group invites to users outside the group when they receive a tip.

In order to manage the +register restriction I would recommend that any +tip requires SteamID for non group members, then invites that ID to the group. We should also include an introduction for newbies so they can learn how/what doge is, or at least point them somewhere where they can learn.

**Comment by petschekr** [comment]
Fixed in v2
