### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by doged** [petschekr/SteamDogeTipBot#18]
hi ryan, im having issues compiling this with tsc.. ive tried tsc bot.ts --module commonjs

keeps breaking when trying to import node modules, such as node-dogecoin, etc.. 

never had to compile from ts to js before, normally id just write the js and run it with forever.. 

any help/advice would be appreciated =]

**Comment by doged** [comment]
ah commonjs.. i had the syntax wrong lol

**Comment by petschekr** [comment]
Haha no problem
Let me know if you have any other problems getting it running

**Comment by doged** [comment]
ok i have one more question, how do i get the sentry hex? and do i just place that in a file n call it sentryfile? thanks!

**Comment by petschekr** [comment]
If you're using an account that has Steam Guard enabled, you can use this program to generate a sentry value:

``` javascript
var Steam = require("steam");
var bot = new Steam.SteamClient();
bot.logOn({
    accountName: "username",
    password: "password",
    authCode: "Steam Guard code that is sent to your email"
});
bot.on("sentry", function(sentry) {
    console.log("Sentry in hex form: " + sentry.toString("hex"));
});
```

This is the format for `auth.json` which you should put in the same directory as `bot.ts` and which contains the login details for your bot's Steam account and the RPC server

``` json
{
    "steam": {
        "accountName": "Steam username",
        "password": "Steam password",
        "shaSentryfile": "Sentry value in hex string format"
    },
    "rpc": {
        "username": "RPC username",
        "password": "RPC password
    }
}
```

**Comment by doged** [comment]
hmm, thats the thing, it only sent me a link to validate the email to my email, but it did have an auth token string at the end of the url, broken into 3 parts, seperated by _'s but when i go to manage steamguard settings and "keep it enabled" it just says contacting steam servers, but does nothing..

**Comment by petschekr** [comment]
So it didn't send you a code?

**Comment by doged** [comment]
no just a link to verify the email lol

**Comment by petschekr** [comment]
Oh well then confirm your email by clicking the link and then you should be
able to get Steam Guard codes normally. Also, remember that you have to
spend at least $5 on Steam in order for your account to get full access to
everything. Valve recently implemented that to stop spammers. Some more
info here:
http://www.gamespot.com/articles/steam-limits-users-who-haven-t-spent-5-to-prevent-/1100-6426742/

**Comment by doged** [comment]
how is it gotten normally? when i try to manage it in steam/settings/ it doesnt ever connect to the server

**Comment by petschekr** [comment]
If your account has Steam Guard on, when you log in from a new device,
you'll get a code sent to your email
If you don't have Steam Guard turned on, you can log in with just a
username and password with no code required

**Comment by doged** [comment]
hmm but i have no way of logging in from the server im setting it up on, its all thru ssh.. unless i can # out the sentry from the bot? and just log in with user/pass?

**Comment by petschekr** [comment]
The way that I did it was I used the program I posted above with a blank
code. Steam rejected the request and sent me an email with a Steam Guard
code which I used with the same program to get a permanent sentry value.

**Comment by doged** [comment]
oh ok i see, that explains lol, i didnt think about running it without the code. cool deal =]

**Comment by petschekr** [comment]
Sure no problem. Let me know if it works or not.

**Comment by doged** [comment]
when i run that js i get: 
 nodejs sentry.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'steam'

**Comment by petschekr** [comment]
You need to install the node-steam module. You can do that by running:

```
npm install steam
```

**Comment by doged** [comment]
http://pastebin.com/wJxYkWnJ

**Comment by doged** [comment]
npm install steam
npm WARN engine steam@0.6.8: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
steam@0.6.8 node_modules/steam
├── buffer-crc32@0.2.5
├── adm-zip@0.4.7
├── bytebuffer@3.5.4 (bufferview@1.0.1, long@2.2.3)
└── protobufjs@4.0.0-b2 (ascli@1.0.0)

**Comment by petschekr** [comment]
You're running an old version of node. You should upgrade node to v0.12 or higher (https://nodejs.org/) or try out io.js (https://iojs.org/en/index.html). Node v0.12 and io.js are basically interchangable but io.js has some new features and a faster release schedule (and therefore also a bit more unstable).

**Comment by doged** [comment]
ok i got the sentry now, do i need to only put it in auth.json or does it need to go into bot.ts before compiling?

**Comment by petschekr** [comment]
Just put it in auth.json in the format that I outlined above. You don't
need to put it anywhere in bot.ts

**Comment by doged** [comment]
does the steam module need to be configured? i keep getting a login error, and a new auth code emailed, and then it generates a new sentry hex

**Comment by petschekr** [comment]
No I don't think it needs to be. You should get a sentry hex from the
program I posted earlier and then use it in auth.json for the bot to use.

**Comment by doged** [comment]
ok so basically, everytime i run bot.js, it tells gives me a login error. im pretty sure whats happening, is after i get the sentry hex, since there is no pause, or proper logoff, steam isnt counting the sentry as correct, and it assumes im still trying to login from a new computer, and sends me a new auth code. how can i get the sentry retrieve js to wait a moment before logging off, and/or verify the account is logged in?

**Comment by doged** [comment]
after i put the sentry into the auth, and run the bot, it just logs me off and sends another auth code in the email.. i have like 10 so far lol

**Comment by doged** [comment]
ok so i have it up and running.. only thing im wondering is.. group chat should work then private message? can anyone in the group message it or do they have to be friends? in which case id have to auto add friend requests..

**Comment by petschekr** [comment]
You can private message people if they're in the group chat already. You can't start a private chat unless the person is already in the group chat. You can't send out friend requests because Steam has a cap of about 250. The bot in this repo responds to private messages that others initiate with the bot.

**Comment by justinvforvendetta** [comment]
@petschekr i know this isnt maintained anymore im guessing.. but im getting stuck in a vicious cycle.. i put the 5 digit auth into the sentry retrieve js, and i get the sentry, put it in auth, and i get a login error. then i get another code in the mail, saying i logged in with my correct credentials but didnt pass steamguard

**Comment by petschekr** [comment]
Hi,
What format is the sentry in?

**Comment by justinvforvendetta** [comment]
ah, i got it. i didnt realize new accounts have to make a 5 dollar purchase from the store before they can enter chat. heh. i just turned steam guard off for now. it came back as a hash from what i can tell. long string is what the script returns after i put the 5 digit one it emails me.

**Comment by petschekr** [comment]
Glad you could fix it. Feel free to let me know if you run into any other issues.
