### ISSUE TITLE
Tipping 1 x10 ^ x (Where x is a negitive number)

### ISSUE THREAD

**Issue by NateEkat** [petschekr/SteamDogeTipBot#7]
This may look like a math equation, but the bot is allowing people to tip currency approximately .0000000000000000000000000001 ( 1 x10^-28) of a doge. Much Problem.

**Comment by petschekr** [comment]
Fixed in f537b91930e267743ee2098a9d6aa02bf6eb01db
Thanks

**Comment by iMagooo** [comment]
Given that Doge coins are abundant (one of their many good qualities), wouldn't simply saying that the shibe must tip/add 1 or more coins be less troublesome then a large decimal?
