### ISSUE TITLE
Users' names aren't updated if they change them

### ISSUE THREAD

**Issue by petschekr** [petschekr/SteamDogeTipBot#9]
If a Steam user changes their name, the bot will mislabel them. Retrieve the name upon opening group chat or so and update their name to match their Steam64 ID.

**Comment by VootLejin** [comment]
In the Chat log a message is brought up whenever a name is changed. If there is some way to capture that it could be used for mid-chat changes. Not yet sure on entering with the same name, but There is probably a way to capture steamID.
Alternatively we could just require another +register when names are changed. Kind of damages usability howerever.

**Comment by petschekr** [comment]
Thank you I'll look into doing this

**Comment by petschekr** [comment]
Ok added this in 8596691 with a dumb mistake fixed in a5ea8e7
